# This is a basic workflow to help you get started with Actions

name: Build-And-Deploy-Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Add build on push to amethyst repo

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 
    # Give it access to writing
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
           python-version: "3.10"
           
      - name: Set up Git
        run: sudo apt install git

      - name: Set up Doxygen
        run: sudo apt install doxygen
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clone Github Amethyst Repo
        run: make github_clone

      - name: Build Doxygen data
        run: make doxygen

      - name: Build Breathe apidoc
        run: make breathe_apidoc

      - name: Build sphinx docs
        run: make sphinx_build
        
      - name: Run ghp-import
        run: ghp-import -n -p -f build/html
